### ISSUE TITLE
ioctl(SIOCGIFINDEX) failed: No such device

### ISSUE THREAD

**Issue by dodoaska** [KiltzX/Wifi-Deauth-Python#1]
sudo python3 start.py                                                                                            1 ⨯

Listing available interfaces
|------------------------|
0 -> wlan0
Select your interface: 0
0

Found 2 processes that could cause trouble.
Kill them using 'airmon-ng check kill' before putting
the card in monitor mode, they will interfere by changing channels
and sometimes putting the interface back in managed mode

    PID Name
    543 NetworkManager
   4696 wpa_supplicant

PHY     Interface       Driver          Chipset

phy1    wlan0           rtl8187         Realtek Semiconductor Corp. RTL8187
                (mac80211 monitor mode already enabled for [phy1]wlan0 on [phy1]wlan0)
Start deauth attack yes y ?:y
Interface wlan0mon: 
ioctl(SIOCGIFINDEX) failed: No such device
Failed initializing wireless card(s): wlan0mon
Insert BSSID from wi-fi victim: 
Insert Channel from wi-fi victim:

**Comment by KiltzX** [comment]
If you see the code, you will understand that I put the hardcoded network interfaces, I will change it to customize it

**Comment by KiltzX** [comment]
I added hotfix, maybe works on your machine now 

https://github.com/KiltzX/Wifi-Deauth-Python/commit/a37874453264e8c2c588bc7e859eb02f1add50b7

I go added in future update check if your interface in monitor mode before choose to start deauth attack direct
Today, if you start using `sudo python3 deauth.py [interface]` starts without wireless adapter scan
